apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pvc-reader
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pvc-reader-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: needednamespace
roleRef:
  kind: ClusterRole
  name: pvc-reader
  apiGroup: rbac.authorization.k8s.io