name: Popeye Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment.'
        required: true
        default: 'load'
        type: choice
        options:
        - dev
        - qa
        - load
        - staging
      source-namespace:
        description: 'Source namespace'
        required: true
      dest-namespace:
        description: 'Destination namespace'
        required: true
      source-pvc:
        description: 'Source pvc name'
        required: true
      dest-pvc:
        description: 'Destination pvc name'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  terragrunt:
    runs-on: ubuntu-latest #runner
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name : Connection to Kubernetes Cluster
        run: |
          aws eks --region us-east-1 update-kubeconfig --name prod-eks-cluster
          
      - name: PV migration
        run: |
           sed  's/needednamespace/${{ github.event.inputs.source-namespace }}/g'  serviceaccount.yaml
           cat serviceaccount.yaml
           