name: Pv Migrate Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment.'
        required: true
        default: 'load'
        type: choice
        options:
        - dev
        - qa
        - load
        - staging
      source-namespace:
        description: 'Source namespace'
        required: true
      dest-namespace:
        description: 'Destination namespace'
        required: true
      source-pvc:
        description: 'Source pvc name'
        required: true
      dest-pvc:
        description: 'Destination pvc name'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  data-migration:
    runs-on: ubuntu-latest #runner
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name : Connection to Kubernetes Cluster
        run: |
          aws eks --region us-east-1 update-kubeconfig --name prod-eks-cluster
          
      - name: Creating ClusterRole
        run: |
           sed -i 's/needednamespace/${{ github.event.inputs.source-namespace }}/g'  serviceaccount.yaml
           kubectl apply -f serviceaccount.yaml 


      - name: PV migrate  Setup
        run: |
           /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
           (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/runner/.bashrc
           eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
           sudo apt-get install build-essential
           brew tap utkuozdemir/pv-migrate
           brew install pv-migrate
           pv-migrate migrate -i --source-namespace ${{ github.event.inputs.source-namespace }} --dest-namespace ${{ github.event.inputs.dest-namespace }} ${{ github.event.inputs.source-pvc }} ${{ github.event.inputs.dest-pvc }}


      - name: Clean up ClusterRole
        run: |
           kubectl delete -f serviceaccount.yaml 